# Site settings
title: Zian (Angel) Chen
twitter_username: Zian_Chen
name: Angel Chen

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
# - title: Blog
#   url: http://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/angelchen34
# - title: StackOverflow
#   url: http://stackoverflow.com/users/258813/rhinds
# - title: DZone
#   url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/zian-chen/

#Any buzzword skills you want to include
skills:
 - Transfer Pricing
 - Economics 
 - Math
 - Python

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Transfer Pricing Associate
   start: 2019
   end: Ongoing
   employer: EY
   description: Building a better working world. 
   
#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2018
   subject: Economics and Mathematics
   school: University of Washington, Seattle

intro: |
  I am a new grad with one year of working experience in the field of transfer pricing. 
  
